let ClassRegistry = require('./lib/classregistry')
let Bar = require('./entities/bar/object')
let BarModel = require('./entities/bar/model')
let BarBeer = require('./entities/barbeer/object')
let BarBeerModel = require('./entities/barbeer/model')
let Beer = require('./entities/beer/object')
let BeerModel = require('./entities/beer/model')
let Brewery = require('./entities/brewery/object')
let BreweryModel = require('./entities/brewery/model')
let Rating = require('./entities/rating/object')
let RatingModel = require('./entities/rating/model')
let User = require('./entities/user/object')
let UserModel = require('./entities/user/model')

let registry = ClassRegistry.shared()

registry.register('Bar', Bar)
registry.register('BarModel', BarModel)
registry.register('BarBeer', BarBeer)
registry.register('BarBeerModel', BarBeerModel)
registry.register('Beer', Beer)
registry.register('BeerModel', BeerModel)
registry.register('Brewery', Brewery)
registry.register('BreweryModel', BreweryModel)
registry.register('Rating', Rating)
registry.register('RatingModel', RatingModel)
registry.register('User', User)
registry.register('UserModel', UserModel)
